import './globals.css'
import { Goudy_Bookletter_1911 } from 'next/font/google'

const inter = Goudy_Bookletter_1911({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="zh-CN">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
